### ISSUE TITLE
Extension Settings

### ISSUE THREAD

**Issue by kaeh** [RockyCott/i18n-peek#2]
Hey, it's me again :grin: 

Could it be possible to add some settings to the extension, to store things like custom directory path ?

**Comment by RockyCott** [comment]
Hey, nice to see you again!

Just to make sure I understand correctly, are you asking if it's possible to add a feature to the extension that stores the last configuration used (like the custom directory path) and applies it automatically when starting a new project? For example, if the last time you used the extension you changed the custom directory from `src/assets/i18n` to `src/app/my-i18n`, then in a new project, the default directory would be `src/app/my-i18n` or the remote directory if that was used. This way, you wouldn't have to set it up from scratch every time.

**Comment by kaeh** [comment]
Nice to see you too :D

I think that it is correct.
I don't know how extensions dev works honnestly, but the ideal, to me, would be to be able to store the path somewhere in the settings.

That way we could have a path inside the project settings, if necessary, or in a user/global settings, with default value set as `src/assets/i18n`

**Comment by RockyCott** [comment]
I understand and agree with your proposal. I will work on adding this feature in the next few days and will let you know once it's done.

Thanks!

**Comment by RockyCott** [comment]
Hey there! :)

I hope everything's going well on your end! First off, sorry for the delay in getting back to you. I was away for a bit, but I'm back now. xd

Regarding your suggestion about storing custom directory paths in the extension's settings, I've implemented a solution that I think will meet your needs. Let me break it down for you:

# Solution Overview

The extension now supports Global Custom Directories. When you set a directory in one project (x), that path is saved in the global custom directories list. In a new project, the extension will automatically attempt to use that previously saved configuration if it exists in the new project. Here's a step-by-step guide:

## Steps to Use Global Custom Directories

### Set a Custom Directory in Your Project

- Set an i18n directory in your project (x). This path will be saved in the global custom directories.

### Use the Custom Directory in a New Project

- Right-click on a folder or inside a file in VSCode.
- Select i18n Peek from the context menu.
- Choose Select custom directory from global custom dirs.
- Pick your previously used directory from the list.

![240620_14h27m11s_screenshot](https://github.com/RockyCott/i18n-peek/assets/67379041/ea413670-9d6b-4ac6-8305-6a587ff88559)

I've thoroughly tested these new features, and while everything seems to be working smoothly, you know how it goes—there might still be a few bugs lurking around! xd I'd really appreciate your feedback to catch any potential issues early on. If you could take a moment to try out these features and share any experiences, suggestions, or issues you encounter, I'd greatly appreciate it!

Thanks!

extension version 0.0.7

**Comment by kaeh** [comment]
Hey, thanks for the update !

The settings update is really nice to read :)

I've tested it a bit and maybe i'm using it wrong but the path saved in the settings seems to be absolute path :sweat_smile: 

That means I can't share the settings with my team, could it be a relative path from the project root ?

Also, could it work with transloco ? It uses `| transloco` instead of `| translate`

**Comment by RockyCott** [comment]
Hey there!

First off, I want to sincerely apologize for the delay in responding to your comment. The notification must have slipped by me, and I only realized now that it was a GitHub issue—sorry about that!

Regarding the issue you raised, I've made some updates based on your feedback:

- Relative Path for Settings: I've updated the extension so that paths are now saved as relative paths from the project root. This should make it easier for you to share settings with your team without running into any path-related issues.

- Transloco: Fortunately, the extension works by reading the i18n paths directly, so it doesn't rely on the `| translate` pipe specifically. This means it should work just fine with `| transloco` or any other similar setup.

Thanks so much for taking the time to test the extension and share your thoughts! If you run into any more issues or have further suggestions, please don't hesitate to let me know.
